import HeaderBar from '@/components/navigations/headerBar';
import { ServiceProvider } from '@/hooks/ServiceProvider';
import { StoreProvider } from '@/hooks/StoreProvider';
import ThemeProvider from '@/hooks/ThemeProvider';
import UiProviders from '@/hooks/UiProvider';
import '@/styles/global.css';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const defaultStore = {};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full w-full" suppressHydrationWarning>
      <body className="h-full w-full">
        <ServiceProvider>
          <StoreProvider initialState={defaultStore}>
            <ThemeProvider attribute="class" defaultTheme="system" themes={['light', 'dark']} enableSystem={true}>
              <main className="no-scrollbar bg-rootBg h-full w-full">
                <UiProviders>
                  <HeaderBar />
                  {children}
                </UiProviders>
              </main>
            </ThemeProvider>
          </StoreProvider>
        </ServiceProvider>
      </body>
    </html>
  );
}
