import HeaderBar from '@/components/navigations/headerBar';
import { ServiceProvider } from '@/hooks/providers/ServiceProvider';
import { StoreProvider } from '@/hooks/providers/StoreProvider';
import UiProviders from '@/hooks/providers/UiProvider';
import '@/styles/global.css';
import type { Metadata } from 'next';
import { ThemeProvider as NextThemesProvider } from 'next-themes';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const defaultStore = {};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full w-full" suppressHydrationWarning>
      <body className="h-full w-full">
        <ServiceProvider>
          <StoreProvider initialState={defaultStore}>
            <main className="no-scrollbar !bg-rootBg min-h-screen w-full">
              <NextThemesProvider
                attribute="class"
                defaultTheme="system"
                themes={['light', 'dark']}
                enableSystem={true}
              >
                <UiProviders>
                  <main className="flex min-h-screen w-full flex-col">
                    <HeaderBar />
                    <div className="relative flex-1">{children}</div>
                  </main>
                </UiProviders>
              </NextThemesProvider>
            </main>
          </StoreProvider>
        </ServiceProvider>
      </body>
    </html>
  );
}
