import { ServiceProvider } from '@/hooks/ServiceProvider';
import { StoreProvider } from '@/hooks/StoreProvider';
import ThemeProvider from '@/hooks/ThemeProvider';
import '@/styles/global.css';
import { Theme as RadixTheme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const defaultStore = {};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="w-full h-full" suppressHydrationWarning>
      <body className="w-full h-full">
        <ServiceProvider>
          <StoreProvider initialState={defaultStore}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
              <RadixTheme accentColor="mint" grayColor="slate" radius="medium" scaling="100%">
                {children}
              </RadixTheme>
            </ThemeProvider>
          </StoreProvider>
        </ServiceProvider>
      </body>
    </html>
  );
}
