import { ServiceProvider } from '@/hooks/ServiceProvider';
import { StoreProvider } from '@/hooks/StoreProvider';
import ThemeProvider from '@/hooks/ThemeProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React from 'react';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
const defaultStore = {};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className} suppressHydrationWarning>
      <body>
        <ServiceProvider>
          <StoreProvider initialState={defaultStore}>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem={true}>
              {children}
            </ThemeProvider>
          </StoreProvider>
        </ServiceProvider>
      </body>
    </html>
  );
}
